"""empty message

Revision ID: 1c77d300ea41
Revises: 58a7a798b9b4
Create Date: 2021-09-11 22:24:23.183420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c77d300ea41'
down_revision = '58a7a798b9b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refund', sa.Column('receipt_number', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refund', 'receipt_number')
    # ### end Alembic commands ###
