"""empty message

Revision ID: 392f8acaaab3
Revises: 09d352d00f1c
Create Date: 2021-04-30 21:19:13.102249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392f8acaaab3'
down_revision = '09d352d00f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('annual_revenue', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.drop_index('ix_public_temptable_index', table_name='temptable')
    op.drop_table('temptable')
    op.add_column('sale_record', sa.Column('office', sa.String(length=50), nullable=True))
    op.add_column('sale_record', sa.Column('teacher_name', sa.String(length=100), nullable=True))
    op.add_column('transaction', sa.Column('service_1_office', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_1_teacher_name', sa.String(length=100), nullable=True))
    op.add_column('transaction', sa.Column('service_2_office', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_2_teacher_name', sa.String(length=100), nullable=True))
    op.add_column('transaction', sa.Column('service_3_office', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_3_teacher_name', sa.String(length=100), nullable=True))
    op.add_column('transaction', sa.Column('service_4_office', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_4_teacher_name', sa.String(length=100), nullable=True))
    op.add_column('transaction', sa.Column('service_5_office', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_5_teacher_name', sa.String(length=100), nullable=True))
    op.add_column('transaction', sa.Column('service_6_office', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_6_teacher_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'service_6_teacher_name')
    op.drop_column('transaction', 'service_6_office')
    op.drop_column('transaction', 'service_5_teacher_name')
    op.drop_column('transaction', 'service_5_office')
    op.drop_column('transaction', 'service_4_teacher_name')
    op.drop_column('transaction', 'service_4_office')
    op.drop_column('transaction', 'service_3_teacher_name')
    op.drop_column('transaction', 'service_3_office')
    op.drop_column('transaction', 'service_2_teacher_name')
    op.drop_column('transaction', 'service_2_office')
    op.drop_column('transaction', 'service_1_teacher_name')
    op.drop_column('transaction', 'service_1_office')
    op.drop_column('sale_record', 'teacher_name')
    op.drop_column('sale_record', 'office')
    op.create_table('temptable',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('school', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('previous_scores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_th', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graduate_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dad_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('know_us_from', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('universal_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('streak_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_country', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_public_temptable_index', 'temptable', ['index'], unique=False)
    op.drop_table('teacher')
    # ### end Alembic commands ###
