"""empty message

Revision ID: 573ce523b694
Revises: 973c325318b6
Create Date: 2021-03-29 21:42:07.155667

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '573ce523b694'
down_revision = '973c325318b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('VAT_info',
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('vat_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('country')
    )
    op.create_table('accounting_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('code_number', sa.String(length=10), nullable=True),
    sa.Column('vat_invoice_code_number', sa.String(length=10), nullable=True),
    sa.Column('receipt_pm_code', sa.String(length=20), nullable=True),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('name_th', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('service', sa.String(length=200), nullable=True),
    sa.Column('service_count', sa.Float(), nullable=True),
    sa.Column('price_per_unit', sa.Float(), nullable=True),
    sa.Column('total_non_vat_amount', sa.Float(), nullable=True),
    sa.Column('tax_invoice_amount', sa.Float(), nullable=True),
    sa.Column('vat_amount', sa.Float(), nullable=True),
    sa.Column('total_vat_amount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('amortization_type', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('hours_per_week', sa.Float(), nullable=True),
    sa.Column('month_1_hrs', sa.Float(), nullable=True),
    sa.Column('month_2_hrs', sa.Float(), nullable=True),
    sa.Column('month_3_hrs', sa.Float(), nullable=True),
    sa.Column('month_4_hrs', sa.Float(), nullable=True),
    sa.Column('month_5_hrs', sa.Float(), nullable=True),
    sa.Column('month_6_hrs', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('non_vat_record')
    op.drop_index('ix_public_temptable_index', table_name='temptable')
    op.drop_table('temptable')
    op.create_foreign_key(None, 'sale_record', 'transaction', ['transaction_id'], ['id'])
    op.add_column('service', sa.Column('default_amortize_duration_month', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('default_amortize_end_day', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('default_amortize_end_month', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('default_amortize_start_day', sa.Integer(), nullable=True))
    op.add_column('service', sa.Column('default_amortize_start_month', sa.Integer(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_amortization_type', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_1_end_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_hours_per_week', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_month_1_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_month_2_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_month_3_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_month_4_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_month_5_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_month_6_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_start_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_amortization_type', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_2_end_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_hours_per_week', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_month_1_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_month_2_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_month_3_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_month_4_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_month_5_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_month_6_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_start_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_amortization_type', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_3_end_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_hours_per_week', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_month_1_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_month_2_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_month_3_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_month_4_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_month_5_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_month_6_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_start_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_amortization_type', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_4_end_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_hours_per_week', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_month_1_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_month_2_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_month_3_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_month_4_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_month_5_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_month_6_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_start_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_amortization_type', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_5_end_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_hours_per_week', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_month_1_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_month_2_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_month_3_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_month_4_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_month_5_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_month_6_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_start_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_amortization_type', sa.String(length=50), nullable=True))
    op.add_column('transaction', sa.Column('service_6_end_date', sa.DateTime(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_hours_per_week', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_month_1_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_month_2_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_month_3_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_month_4_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_month_5_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_month_6_hrs', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_start_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_transaction_service_1_end_date'), 'transaction', ['service_1_end_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_1_start_date'), 'transaction', ['service_1_start_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_2_end_date'), 'transaction', ['service_2_end_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_2_start_date'), 'transaction', ['service_2_start_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_3_end_date'), 'transaction', ['service_3_end_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_3_start_date'), 'transaction', ['service_3_start_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_4_end_date'), 'transaction', ['service_4_end_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_4_start_date'), 'transaction', ['service_4_start_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_5_end_date'), 'transaction', ['service_5_end_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_5_start_date'), 'transaction', ['service_5_start_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_6_end_date'), 'transaction', ['service_6_end_date'], unique=False)
    op.create_index(op.f('ix_transaction_service_6_start_date'), 'transaction', ['service_6_start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_service_6_start_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_6_end_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_5_start_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_5_end_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_4_start_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_4_end_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_3_start_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_3_end_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_2_start_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_2_end_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_1_start_date'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_service_1_end_date'), table_name='transaction')
    op.drop_column('transaction', 'service_6_start_date')
    op.drop_column('transaction', 'service_6_month_6_hrs')
    op.drop_column('transaction', 'service_6_month_5_hrs')
    op.drop_column('transaction', 'service_6_month_4_hrs')
    op.drop_column('transaction', 'service_6_month_3_hrs')
    op.drop_column('transaction', 'service_6_month_2_hrs')
    op.drop_column('transaction', 'service_6_month_1_hrs')
    op.drop_column('transaction', 'service_6_hours_per_week')
    op.drop_column('transaction', 'service_6_end_date')
    op.drop_column('transaction', 'service_6_amortization_type')
    op.drop_column('transaction', 'service_5_start_date')
    op.drop_column('transaction', 'service_5_month_6_hrs')
    op.drop_column('transaction', 'service_5_month_5_hrs')
    op.drop_column('transaction', 'service_5_month_4_hrs')
    op.drop_column('transaction', 'service_5_month_3_hrs')
    op.drop_column('transaction', 'service_5_month_2_hrs')
    op.drop_column('transaction', 'service_5_month_1_hrs')
    op.drop_column('transaction', 'service_5_hours_per_week')
    op.drop_column('transaction', 'service_5_end_date')
    op.drop_column('transaction', 'service_5_amortization_type')
    op.drop_column('transaction', 'service_4_start_date')
    op.drop_column('transaction', 'service_4_month_6_hrs')
    op.drop_column('transaction', 'service_4_month_5_hrs')
    op.drop_column('transaction', 'service_4_month_4_hrs')
    op.drop_column('transaction', 'service_4_month_3_hrs')
    op.drop_column('transaction', 'service_4_month_2_hrs')
    op.drop_column('transaction', 'service_4_month_1_hrs')
    op.drop_column('transaction', 'service_4_hours_per_week')
    op.drop_column('transaction', 'service_4_end_date')
    op.drop_column('transaction', 'service_4_amortization_type')
    op.drop_column('transaction', 'service_3_start_date')
    op.drop_column('transaction', 'service_3_month_6_hrs')
    op.drop_column('transaction', 'service_3_month_5_hrs')
    op.drop_column('transaction', 'service_3_month_4_hrs')
    op.drop_column('transaction', 'service_3_month_3_hrs')
    op.drop_column('transaction', 'service_3_month_2_hrs')
    op.drop_column('transaction', 'service_3_month_1_hrs')
    op.drop_column('transaction', 'service_3_hours_per_week')
    op.drop_column('transaction', 'service_3_end_date')
    op.drop_column('transaction', 'service_3_amortization_type')
    op.drop_column('transaction', 'service_2_start_date')
    op.drop_column('transaction', 'service_2_month_6_hrs')
    op.drop_column('transaction', 'service_2_month_5_hrs')
    op.drop_column('transaction', 'service_2_month_4_hrs')
    op.drop_column('transaction', 'service_2_month_3_hrs')
    op.drop_column('transaction', 'service_2_month_2_hrs')
    op.drop_column('transaction', 'service_2_month_1_hrs')
    op.drop_column('transaction', 'service_2_hours_per_week')
    op.drop_column('transaction', 'service_2_end_date')
    op.drop_column('transaction', 'service_2_amortization_type')
    op.drop_column('transaction', 'service_1_start_date')
    op.drop_column('transaction', 'service_1_month_6_hrs')
    op.drop_column('transaction', 'service_1_month_5_hrs')
    op.drop_column('transaction', 'service_1_month_4_hrs')
    op.drop_column('transaction', 'service_1_month_3_hrs')
    op.drop_column('transaction', 'service_1_month_2_hrs')
    op.drop_column('transaction', 'service_1_month_1_hrs')
    op.drop_column('transaction', 'service_1_hours_per_week')
    op.drop_column('transaction', 'service_1_end_date')
    op.drop_column('transaction', 'service_1_amortization_type')
    op.drop_column('service', 'default_amortize_start_month')
    op.drop_column('service', 'default_amortize_start_day')
    op.drop_column('service', 'default_amortize_end_month')
    op.drop_column('service', 'default_amortize_end_day')
    op.drop_column('service', 'default_amortize_duration_month')
    op.drop_constraint(None, 'sale_record', type_='foreignkey')
    op.create_table('temptable',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('previous_scores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_th', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('streak_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graduate_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('dad_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('know_us_from', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('universal_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('school', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_country', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_public_temptable_index', 'temptable', ['index'], unique=False)
    op.create_table('non_vat_record',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('code_number', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('receipt_pm_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('name_th', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('address', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('service', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('service_count', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_per_unit', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], name='non_vat_record_transaction_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='non_vat_record_pkey')
    )
    op.drop_table('accounting_record')
    op.drop_table('VAT_info')
    # ### end Alembic commands ###
