"""empty message

Revision ID: 973c325318b6
Revises: 16161b125517
Create Date: 2021-03-16 16:33:16.634679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973c325318b6'
down_revision = '16161b125517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('QIR_numbers_preview', sa.Column('code_number', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('QIR_numbers_preview', 'code_number')
    # ### end Alembic commands ###
