"""empty message

Revision ID: a75ab6b83dfc
Revises: 573ce523b694
Create Date: 2021-03-31 22:33:07.284786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75ab6b83dfc'
down_revision = '573ce523b694'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_public_temptable_index', table_name='temptable')
    op.drop_table('temptable')
    op.add_column('accounting_record', sa.Column('friday_hrs', sa.Float(), nullable=True))
    op.add_column('accounting_record', sa.Column('monday_hrs', sa.Float(), nullable=True))
    op.add_column('accounting_record', sa.Column('saturday_hrs', sa.Float(), nullable=True))
    op.add_column('accounting_record', sa.Column('sunday_hrs', sa.Float(), nullable=True))
    op.add_column('accounting_record', sa.Column('thursday_hrs', sa.Float(), nullable=True))
    op.add_column('accounting_record', sa.Column('tuesday_hrs', sa.Float(), nullable=True))
    op.add_column('accounting_record', sa.Column('wednesday_hrs', sa.Float(), nullable=True))
    op.add_column('student', sa.Column('company_address', sa.String(length=200), nullable=True))
    op.add_column('student', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('student', sa.Column('company_tax_id', sa.String(length=40), nullable=True))
    op.add_column('transaction', sa.Column('company_address', sa.String(length=200), nullable=True))
    op.add_column('transaction', sa.Column('company_name', sa.String(length=200), nullable=True))
    op.add_column('transaction', sa.Column('company_tax_id', sa.String(length=40), nullable=True))
    op.add_column('transaction', sa.Column('service_1_friday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_monday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_saturday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_sunday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_thursday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_tuesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_1_wednesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_friday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_monday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_saturday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_sunday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_thursday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_tuesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_2_wednesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_friday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_monday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_saturday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_sunday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_thursday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_tuesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_3_wednesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_friday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_monday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_saturday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_sunday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_thursday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_tuesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_4_wednesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_friday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_monday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_saturday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_sunday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_thursday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_tuesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_5_wednesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_friday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_monday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_saturday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_sunday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_thursday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_tuesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('service_6_wednesday_hours', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('use_company_info_flag', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'use_company_info_flag')
    op.drop_column('transaction', 'service_6_wednesday_hours')
    op.drop_column('transaction', 'service_6_tuesday_hours')
    op.drop_column('transaction', 'service_6_thursday_hours')
    op.drop_column('transaction', 'service_6_sunday_hours')
    op.drop_column('transaction', 'service_6_saturday_hours')
    op.drop_column('transaction', 'service_6_monday_hours')
    op.drop_column('transaction', 'service_6_friday_hours')
    op.drop_column('transaction', 'service_5_wednesday_hours')
    op.drop_column('transaction', 'service_5_tuesday_hours')
    op.drop_column('transaction', 'service_5_thursday_hours')
    op.drop_column('transaction', 'service_5_sunday_hours')
    op.drop_column('transaction', 'service_5_saturday_hours')
    op.drop_column('transaction', 'service_5_monday_hours')
    op.drop_column('transaction', 'service_5_friday_hours')
    op.drop_column('transaction', 'service_4_wednesday_hours')
    op.drop_column('transaction', 'service_4_tuesday_hours')
    op.drop_column('transaction', 'service_4_thursday_hours')
    op.drop_column('transaction', 'service_4_sunday_hours')
    op.drop_column('transaction', 'service_4_saturday_hours')
    op.drop_column('transaction', 'service_4_monday_hours')
    op.drop_column('transaction', 'service_4_friday_hours')
    op.drop_column('transaction', 'service_3_wednesday_hours')
    op.drop_column('transaction', 'service_3_tuesday_hours')
    op.drop_column('transaction', 'service_3_thursday_hours')
    op.drop_column('transaction', 'service_3_sunday_hours')
    op.drop_column('transaction', 'service_3_saturday_hours')
    op.drop_column('transaction', 'service_3_monday_hours')
    op.drop_column('transaction', 'service_3_friday_hours')
    op.drop_column('transaction', 'service_2_wednesday_hours')
    op.drop_column('transaction', 'service_2_tuesday_hours')
    op.drop_column('transaction', 'service_2_thursday_hours')
    op.drop_column('transaction', 'service_2_sunday_hours')
    op.drop_column('transaction', 'service_2_saturday_hours')
    op.drop_column('transaction', 'service_2_monday_hours')
    op.drop_column('transaction', 'service_2_friday_hours')
    op.drop_column('transaction', 'service_1_wednesday_hours')
    op.drop_column('transaction', 'service_1_tuesday_hours')
    op.drop_column('transaction', 'service_1_thursday_hours')
    op.drop_column('transaction', 'service_1_sunday_hours')
    op.drop_column('transaction', 'service_1_saturday_hours')
    op.drop_column('transaction', 'service_1_monday_hours')
    op.drop_column('transaction', 'service_1_friday_hours')
    op.drop_column('transaction', 'company_tax_id')
    op.drop_column('transaction', 'company_name')
    op.drop_column('transaction', 'company_address')
    op.drop_column('student', 'company_tax_id')
    op.drop_column('student', 'company_name')
    op.drop_column('student', 'company_address')
    op.drop_column('accounting_record', 'wednesday_hrs')
    op.drop_column('accounting_record', 'tuesday_hrs')
    op.drop_column('accounting_record', 'thursday_hrs')
    op.drop_column('accounting_record', 'sunday_hrs')
    op.drop_column('accounting_record', 'saturday_hrs')
    op.drop_column('accounting_record', 'monday_hrs')
    op.drop_column('accounting_record', 'friday_hrs')
    op.create_table('temptable',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('school', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('know_us_from', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graduate_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mom_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('universal_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('streak_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('previous_scores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_th', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_country', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_public_temptable_index', 'temptable', ['index'], unique=False)
    # ### end Alembic commands ###
