"""empty message

Revision ID: ec03b05a30d1
Revises: 1a8647fc487e
Create Date: 2021-05-23 21:26:58.899741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec03b05a30d1'
down_revision = '1a8647fc487e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_machine',
    sa.Column('machine_code_number', sa.Integer(), nullable=False),
    sa.Column('reference_name', sa.String(length=20), nullable=True),
    sa.Column('bank_name', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('machine_code_number')
    )
    op.drop_index('ix_public_temptable_index', table_name='temptable')
    op.drop_table('temptable')
    op.add_column('accounting_record', sa.Column('amortization_start_date', sa.DateTime(), nullable=True))
    op.add_column('accounting_record', sa.Column('card_issuer', sa.String(length=100), nullable=True))
    op.add_column('accounting_record', sa.Column('card_machine', sa.String(length=100), nullable=True))
    op.add_column('accounting_record', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('accounting_record', sa.Column('payment_method', sa.String(length=50), nullable=True))
    op.add_column('accounting_record', sa.Column('payment_time', sa.Time(), nullable=True))
    op.add_column('accounting_record', sa.Column('service_category', sa.String(length=50), nullable=True))
    op.add_column('accounting_record', sa.Column('service_subcategory', sa.String(length=50), nullable=True))
    op.add_column('sale_record', sa.Column('amortization_start_date', sa.DateTime(), nullable=True))
    op.add_column('sale_record', sa.Column('card_issuer', sa.String(length=100), nullable=True))
    op.add_column('sale_record', sa.Column('card_machine', sa.String(length=100), nullable=True))
    op.add_column('sale_record', sa.Column('payment_date', sa.Date(), nullable=True))
    op.add_column('sale_record', sa.Column('payment_time', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sale_record', 'payment_time')
    op.drop_column('sale_record', 'payment_date')
    op.drop_column('sale_record', 'card_machine')
    op.drop_column('sale_record', 'card_issuer')
    op.drop_column('sale_record', 'amortization_start_date')
    op.drop_column('accounting_record', 'service_subcategory')
    op.drop_column('accounting_record', 'service_category')
    op.drop_column('accounting_record', 'payment_time')
    op.drop_column('accounting_record', 'payment_method')
    op.drop_column('accounting_record', 'payment_date')
    op.drop_column('accounting_record', 'card_machine')
    op.drop_column('accounting_record', 'card_issuer')
    op.drop_column('accounting_record', 'amortization_start_date')
    op.create_table('temptable',
    sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('name_th', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('previous_scores', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dad_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('universal_id', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('streak_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('graduate_year', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('mom_line', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('know_us_from', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_mobile_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('school', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tax_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('mom_email', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('student_country', sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.create_index('ix_public_temptable_index', 'temptable', ['index'], unique=False)
    op.drop_table('card_machine')
    # ### end Alembic commands ###
